// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _5_3_2022.Models;

namespace _5_3_2022.Migrations
{
    [DbContext(typeof(booksContext))]
    partial class booksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_5_3_2022.Models.Kniga", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Author")
                        .HasColumnName("Author")
                        .HasMaxLength(10);

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasMaxLength(10);

                    b.Property<int>("Price")
                        .HasColumnName("Price");

                    b.Property<string>("Publisher")
                        .HasColumnName("Publisher")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.ToTable("Knigi");
                });
#pragma warning restore 612, 618
        }
    }
}
